gcp_credentials          = "gcp_keys.json"
gcp_project_id           = "micro-chiller-370322"
gcp_region               = "us-central1"
gcp_cluster_name         = "k8s-task-cluster"
gcp_region_zones         = ["us-central1-a", "us-central1-b", "us-central1-f"]
gke_network              = "default"
gke_subnetwork           = "default"
gke_node_pool_name       = "k8s-task-node-pool"
gke_service_account_name = "terraform-sa@micro-chiller-370322.iam.gserviceaccount.com"
